/* =============================================================================
   Hola Herron — Spanish course content (Castilian / Spain)
   -----------------------------------------------------------------------------
   Structure:
     LEVELS[]  -> { id, code, title, blurb, lessons[] }
       lesson  -> { id, title, goal, tip?, grammar?, items[] }
         item  -> { es, en, hint, note? }
            es   = Spanish (what the app speaks & you copy)
            en   = English meaning
            hint = English-friendly pronunciation (STRESS in caps; 'th' = soft c/z)
            note = optional culture / grammar nugget

   Pronunciation guide baked into the hints:
     - 'th' is the Castilian soft sound for c (before e/i) and z  ->  gracias = GRAH-thyahs
     - 'h' on its own is silent in Spanish (hola = OH-lah)
     - 'j' and soft 'g' = a throaty H, written 'kh'  ->  jamón = kha-MON
     - rolled r shown as 'rr'
   This file is plain data so you can add lessons easily — see README.
   ========================================================================== */

const LEVELS = [
  /* ===========================================================================
     LEVEL A — HOLIDAY SURVIVAL
     ======================================================================== */
  {
    id: "A",
    code: "A",
    title: "Holiday Survival",
    blurb: "The essentials to feel confident from day one in Spain.",
    lessons: [
      {
        id: "a1",
        title: "Greetings & being polite",
        goal: "Say hello, please and thank you like a local.",
        tip: "Spaniards are warm and polite — a friendly 'Hola, buenos días' opens every door.",
        items: [
          { es: "Hola", en: "Hello / Hi", hint: "OH-lah", note: "The 'h' is silent." },
          { es: "Buenos días", en: "Good morning", hint: "BWEH-nos DEE-as", note: "Used until about 2pm." },
          { es: "Buenas tardes", en: "Good afternoon / evening", hint: "BWEH-nas TAR-des", note: "From about 2pm until dark." },
          { es: "Buenas noches", en: "Good night", hint: "BWEH-nas NO-ches" },
          { es: "Adiós", en: "Goodbye", hint: "ah-DYOS" },
          { es: "Hasta luego", en: "See you later", hint: "AS-tah LWEH-go", note: "Heard far more than 'adiós' day to day." },
          { es: "Por favor", en: "Please", hint: "por fah-VOR" },
          { es: "Gracias", en: "Thank you", hint: "GRAH-thyahs" },
          { es: "Muchas gracias", en: "Thank you very much", hint: "MOO-chas GRAH-thyahs" },
          { es: "De nada", en: "You're welcome", hint: "deh NAH-dah" },
          { es: "Sí", en: "Yes", hint: "see" },
          { es: "No", en: "No", hint: "no" },
          { es: "Perdón", en: "Sorry / Excuse me", hint: "per-DON", note: "To apologise or get attention." },
          { es: "Disculpe", en: "Excuse me (politely)", hint: "dis-KOOL-peh", note: "Polite way to stop a stranger or waiter." },
          { es: "Lo siento", en: "I'm sorry", hint: "lo SYEN-to" },
        ],
      },
      {
        id: "a2",
        title: "First conversation",
        goal: "Greet someone, ask how they are and introduce yourself.",
        grammar: "Spanish has two words for 'you': <b>tú</b> (informal, friends/family) and <b>usted</b> (formal, strangers/older people). On holiday, <b>usted</b> is the safe, respectful choice with staff and people you don't know.",
        items: [
          { es: "¿Qué tal?", en: "How's it going?", hint: "keh tal", note: "Casual and very common." },
          { es: "¿Cómo está usted?", en: "How are you? (formal)", hint: "KO-mo es-TA oos-TED" },
          { es: "Muy bien, gracias", en: "Very well, thank you", hint: "mwee byen GRAH-thyahs" },
          { es: "Bien, ¿y usted?", en: "Fine, and you?", hint: "byen, ee oos-TED" },
          { es: "Más o menos", en: "So-so", hint: "mas o MEH-nos" },
          { es: "¿Cómo se llama?", en: "What's your name? (formal)", hint: "KO-mo seh YAH-mah" },
          { es: "Me llamo Barry", en: "My name is Barry", hint: "meh YAH-mo" },
          { es: "Encantado", en: "Pleased to meet you (man)", hint: "en-kan-TAH-do", note: "A woman says 'encantada'." },
          { es: "Encantada", en: "Pleased to meet you (woman)", hint: "en-kan-TAH-dah" },
          { es: "Mucho gusto", en: "Nice to meet you", hint: "MOO-cho GOOS-to" },
          { es: "¿De dónde es usted?", en: "Where are you from?", hint: "deh DON-deh es oos-TED" },
          { es: "Soy de Inglaterra", en: "I'm from England", hint: "soy deh een-glah-TEH-rrah" },
          { es: "Soy inglés", en: "I'm English (man)", hint: "soy een-GLES", note: "A woman says 'inglesa'." },
          { es: "No hablo mucho español", en: "I don't speak much Spanish", hint: "no AH-blo MOO-cho es-pan-YOL" },
        ],
      },
      {
        id: "a3",
        title: "Numbers 0–20",
        goal: "Count, give your room number and understand small prices.",
        tip: "You'll use these constantly — for prices, room numbers, bus stops and times.",
        items: [
          { es: "cero", en: "0", hint: "THEH-ro" },
          { es: "uno", en: "1", hint: "OO-no" },
          { es: "dos", en: "2", hint: "dos" },
          { es: "tres", en: "3", hint: "tres" },
          { es: "cuatro", en: "4", hint: "KWAH-tro" },
          { es: "cinco", en: "5", hint: "THEEN-ko" },
          { es: "seis", en: "6", hint: "says" },
          { es: "siete", en: "7", hint: "SYEH-teh" },
          { es: "ocho", en: "8", hint: "OH-cho" },
          { es: "nueve", en: "9", hint: "NWEH-veh" },
          { es: "diez", en: "10", hint: "dyeth" },
          { es: "once", en: "11", hint: "ON-theh" },
          { es: "doce", en: "12", hint: "DO-theh" },
          { es: "trece", en: "13", hint: "TREH-theh" },
          { es: "catorce", en: "14", hint: "kah-TOR-theh" },
          { es: "quince", en: "15", hint: "KEEN-theh" },
          { es: "dieciséis", en: "16", hint: "dyeth-ee-SAYS" },
          { es: "diecisiete", en: "17", hint: "dyeth-ee-SYEH-teh" },
          { es: "dieciocho", en: "18", hint: "dyeth-ee-OH-cho" },
          { es: "diecinueve", en: "19", hint: "dyeth-ee-NWEH-veh" },
          { es: "veinte", en: "20", hint: "VAYN-teh" },
        ],
      },
      {
        id: "a4",
        title: "At the café & bar",
        goal: "Order coffee, a beer and a snack with confidence.",
        tip: "In Spain you often order at the bar or get the waiter's attention with 'Perdone'. A small beer is a 'caña'.",
        items: [
          { es: "Una mesa para dos, por favor", en: "A table for two, please", hint: "OO-nah MEH-sah PAH-rah dos" },
          { es: "La carta, por favor", en: "The menu, please", hint: "lah KAR-tah" },
          { es: "Un café con leche", en: "A coffee with milk", hint: "oon kah-FEH kon LEH-cheh" },
          { es: "Un café solo", en: "A black coffee (espresso)", hint: "oon kah-FEH SO-lo" },
          { es: "Un té, por favor", en: "A tea, please", hint: "oon teh" },
          { es: "Una caña", en: "A small draught beer", hint: "OO-nah KAH-nyah", note: "The classic Spanish bar order." },
          { es: "Una cerveza", en: "A beer", hint: "OO-nah ther-VEH-thah" },
          { es: "Una copa de vino tinto", en: "A glass of red wine", hint: "OO-nah KO-pah deh VEE-no TEEN-to" },
          { es: "Vino blanco", en: "White wine", hint: "VEE-no BLAN-ko" },
          { es: "Agua sin gas", en: "Still water", hint: "AH-gwah seen gas" },
          { es: "Agua con gas", en: "Sparkling water", hint: "AH-gwah kon gas" },
          { es: "¿Qué tapas tienen?", en: "What tapas do you have?", hint: "keh TAH-pas TYEH-nen" },
          { es: "Para mí, una tortilla", en: "For me, a Spanish omelette", hint: "PAH-rah mee OO-nah tor-TEE-yah" },
          { es: "¿Algo más?", en: "Anything else? (you'll hear this)", hint: "AL-go mas" },
          { es: "Nada más, gracias", en: "Nothing else, thanks", hint: "NAH-dah mas" },
        ],
      },
      {
        id: "a5",
        title: "At the restaurant",
        goal: "Order a meal and ask for the bill.",
        tip: "Lunch (la comida) is the big meal, often 2–4pm. Dinner (la cena) is late, from 9pm.",
        items: [
          { es: "Tengo una reserva", en: "I have a reservation", hint: "TEN-go OO-nah reh-SER-vah" },
          { es: "¿Qué recomienda?", en: "What do you recommend?", hint: "keh reh-ko-MYEN-dah" },
          { es: "De primero, una sopa", en: "For starters, a soup", hint: "deh pree-MEH-ro OO-nah SO-pah" },
          { es: "De segundo, pescado", en: "For the main, fish", hint: "deh seh-GOON-do pes-KAH-do" },
          { es: "Carne", en: "Meat", hint: "KAR-neh" },
          { es: "Pollo", en: "Chicken", hint: "PO-yo" },
          { es: "Una ensalada", en: "A salad", hint: "OO-nah en-sah-LAH-dah" },
          { es: "El menú del día", en: "The set menu of the day", hint: "el meh-NOO del DEE-ah", note: "Great value — usually 3 courses with a drink." },
          { es: "Soy vegetariano", en: "I'm vegetarian (man)", hint: "soy veh-kheh-tah-RYAH-no", note: "Woman: 'vegetariana'." },
          { es: "Soy alérgico a los frutos secos", en: "I'm allergic to nuts", hint: "soy ah-LER-khee-ko ah los FROO-tos SEH-kos" },
          { es: "Está muy rico", en: "It's delicious", hint: "es-TA mwee REE-ko" },
          { es: "La cuenta, por favor", en: "The bill, please", hint: "lah KWEN-tah" },
          { es: "¿Está incluido el servicio?", en: "Is service included?", hint: "es-TA een-kloo-EE-do el ser-VEE-thyo" },
          { es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", hint: "PWEH-do pah-GAR kon tar-KHEH-tah" },
        ],
      },
      {
        id: "a6",
        title: "Directions & getting around",
        goal: "Ask the way and understand the answer.",
        grammar: "<b>¿Dónde está…?</b> = 'Where is…?'. Pair it with 'el' (masculine) or 'la' (feminine): <i>el baño</i> (the toilet), <i>la playa</i> (the beach).",
        items: [
          { es: "¿Dónde está el baño?", en: "Where is the toilet?", hint: "DON-deh es-TA el BAH-nyo" },
          { es: "¿Dónde está la playa?", en: "Where is the beach?", hint: "DON-deh es-TA lah PLAH-yah" },
          { es: "¿Cómo llego al centro?", en: "How do I get to the centre?", hint: "KO-mo YEH-go al THEN-tro" },
          { es: "¿Está lejos?", en: "Is it far?", hint: "es-TA LEH-khos" },
          { es: "Está cerca", en: "It's near", hint: "es-TA THER-kah" },
          { es: "Todo recto", en: "Straight ahead", hint: "TO-do REK-to" },
          { es: "A la derecha", en: "To the right", hint: "ah lah deh-REH-chah" },
          { es: "A la izquierda", en: "To the left", hint: "ah lah eeth-KYER-dah" },
          { es: "La primera calle", en: "The first street", hint: "lah pree-MEH-rah KAH-yeh" },
          { es: "Gire aquí", en: "Turn here", hint: "KHEE-reh ah-KEE" },
          { es: "¿Hay un cajero cerca?", en: "Is there a cash machine nearby?", hint: "eye oon kah-KHEH-ro THER-kah" },
          { es: "Estoy perdido", en: "I'm lost (man)", hint: "es-TOY per-DEE-do", note: "Woman: 'perdida'." },
          { es: "¿Puede ayudarme?", en: "Can you help me?", hint: "PWEH-deh ah-yoo-DAR-meh" },
          { es: "¿Dónde está la parada de autobús?", en: "Where's the bus stop?", hint: "DON-deh es-TA lah pah-RAH-dah deh ow-to-BOOS" },
        ],
      },
      {
        id: "a7",
        title: "Shopping & paying",
        goal: "Buy things at the market or shop and handle money.",
        tip: "Markets are brilliant for practising. 'Me pone…' (literally 'put me…') is the natural way to order at a counter.",
        items: [
          { es: "¿Cuánto cuesta?", en: "How much is it?", hint: "KWAN-to KWES-tah" },
          { es: "¿Cuánto es todo?", en: "How much is it all?", hint: "KWAN-to es TO-do" },
          { es: "Es caro", en: "It's expensive", hint: "es KAH-ro" },
          { es: "Es barato", en: "It's cheap", hint: "es bah-RAH-to" },
          { es: "Me pone un kilo de tomates", en: "A kilo of tomatoes, please", hint: "meh PO-neh oon KEE-lo deh to-MAH-tes" },
          { es: "Medio kilo", en: "Half a kilo", hint: "MEH-dyo KEE-lo" },
          { es: "Quería esto", en: "I'd like this one", hint: "keh-REE-ah ES-to", note: "Point and say it — works every time." },
          { es: "¿Tiene una talla más grande?", en: "Do you have a bigger size?", hint: "TYEH-neh OO-nah TAH-yah mas GRAN-deh" },
          { es: "Más pequeño", en: "Smaller", hint: "mas peh-KEH-nyo" },
          { es: "Solo estoy mirando", en: "I'm just looking", hint: "SO-lo es-TOY mee-RAN-do" },
          { es: "Me lo llevo", en: "I'll take it", hint: "meh lo YEH-vo" },
          { es: "¿Acepta tarjeta?", en: "Do you take card?", hint: "ah-THEP-tah tar-KHEH-tah" },
          { es: "En efectivo", en: "In cash", hint: "en eh-fek-TEE-vo" },
          { es: "¿Me da una bolsa?", en: "Can I have a bag?", hint: "meh dah OO-nah BOL-sah" },
        ],
      },
      {
        id: "a8",
        title: "Hotel & accommodation",
        goal: "Check in and sort out your room.",
        items: [
          { es: "Tengo una habitación reservada", en: "I have a room booked", hint: "TEN-go OO-nah ah-bee-tah-THYON reh-ser-VAH-dah" },
          { es: "Una habitación doble", en: "A double room", hint: "OO-nah ah-bee-tah-THYON DO-bleh" },
          { es: "Para tres noches", en: "For three nights", hint: "PAH-rah tres NO-ches" },
          { es: "¿A qué hora es el desayuno?", en: "What time is breakfast?", hint: "ah keh OH-rah es el deh-sah-YOO-no" },
          { es: "¿Tienen wifi?", en: "Do you have wifi?", hint: "TYEH-nen WEE-fee" },
          { es: "¿Cuál es la contraseña?", en: "What's the password?", hint: "kwal es lah kon-trah-SEH-nyah" },
          { es: "El aire acondicionado no funciona", en: "The air conditioning isn't working", hint: "el EYE-reh ah-kon-dee-thyo-NAH-do no foon-THYO-nah" },
          { es: "No hay agua caliente", en: "There's no hot water", hint: "no eye AH-gwah kah-LYEN-teh" },
          { es: "Una toalla más, por favor", en: "One more towel, please", hint: "OO-nah to-AH-yah mas" },
          { es: "¿A qué hora es la salida?", en: "What time is check-out?", hint: "ah keh OH-rah es lah sah-LEE-dah" },
          { es: "¿Puedo dejar las maletas?", en: "Can I leave my luggage?", hint: "PWEH-do deh-KHAR las mah-LEH-tas" },
          { es: "La llave de la habitación", en: "The room key", hint: "lah YAH-veh deh lah ah-bee-tah-THYON" },
        ],
      },
      {
        id: "a9",
        title: "Emergencies & the pharmacy",
        goal: "Get help and explain you feel unwell. Useful and reassuring to know.",
        tip: "Pharmacies (la farmacia, green cross sign) are excellent in Spain for minor problems. The emergency number is 112.",
        items: [
          { es: "¡Ayuda!", en: "Help!", hint: "ah-YOO-dah" },
          { es: "Llame a la policía", en: "Call the police", hint: "YAH-meh ah lah po-lee-THEE-ah" },
          { es: "Llame a una ambulancia", en: "Call an ambulance", hint: "YAH-meh ah OO-nah am-boo-LAN-thyah" },
          { es: "Necesito un médico", en: "I need a doctor", hint: "neh-theh-SEE-to oon MEH-dee-ko" },
          { es: "Me encuentro mal", en: "I feel unwell", hint: "meh en-KWEN-tro mal" },
          { es: "Me duele la cabeza", en: "My head hurts", hint: "meh DWEH-leh lah kah-BEH-thah" },
          { es: "Me duele el estómago", en: "My stomach hurts", hint: "meh DWEH-leh el es-TO-mah-go" },
          { es: "¿Dónde está la farmacia?", en: "Where's the pharmacy?", hint: "DON-deh es-TA lah far-MAH-thyah" },
          { es: "Algo para el dolor", en: "Something for the pain", hint: "AL-go PAH-rah el do-LOR" },
          { es: "Soy alérgico a la penicilina", en: "I'm allergic to penicillin", hint: "soy ah-LER-khee-ko ah lah peh-nee-thee-LEE-nah" },
          { es: "He perdido el pasaporte", en: "I've lost my passport", hint: "eh per-DEE-do el pah-sah-POR-teh" },
          { es: "Me han robado", en: "I've been robbed", hint: "meh an ro-BAH-do" },
        ],
      },
    ],
  },

  /* ===========================================================================
     LEVEL B — GETTING BY
     ======================================================================== */
  {
    id: "B",
    code: "B",
    title: "Getting By",
    blurb: "Hold a friendly chat, handle money and talk about your place in Spain.",
    lessons: [
      {
        id: "b1",
        title: "Small talk with the neighbours",
        goal: "Have the friendly back-and-forth that builds real connections.",
        tip: "This is gold for your holiday-home plan — neighbours who like you make all the difference.",
        items: [
          { es: "¿Vive aquí?", en: "Do you live here?", hint: "VEE-veh ah-KEE" },
          { es: "Estamos de vacaciones", en: "We're on holiday", hint: "es-TAH-mos deh vah-kah-THYO-nes" },
          { es: "Nos encanta este pueblo", en: "We love this town", hint: "nos en-KAN-tah ES-teh PWEH-blo" },
          { es: "Queremos comprar una casa aquí", en: "We want to buy a house here", hint: "keh-REH-mos kom-PRAR OO-nah KAH-sah ah-KEE" },
          { es: "¿Hace mucho que vive aquí?", en: "Have you lived here long?", hint: "AH-theh MOO-cho keh VEE-veh ah-KEE" },
          { es: "¡Qué bonito!", en: "How lovely!", hint: "keh bo-NEE-to" },
          { es: "¿Qué tiempo hace en invierno?", en: "What's the weather like in winter?", hint: "keh TYEM-po AH-theh en een-VYER-no" },
          { es: "¿Hay buenos restaurantes por aquí?", en: "Are there good restaurants around here?", hint: "eye BWEH-nos res-tow-RAN-tes por ah-KEE" },
          { es: "Tenemos que irnos", en: "We have to go", hint: "teh-NEH-mos keh EER-nos" },
          { es: "Ha sido un placer", en: "It's been a pleasure", hint: "ah SEE-do oon plah-THER" },
          { es: "Nos vemos pronto", en: "See you soon", hint: "nos VEH-mos PRON-to" },
          { es: "Cuídese", en: "Take care (formal)", hint: "KWEE-deh-seh" },
        ],
      },
      {
        id: "b2",
        title: "Family & people",
        goal: "Talk about who you are with and describe people.",
        grammar: "'My' changes with number: <b>mi</b> hermano (my brother), <b>mis</b> hermanos (my brothers). Adjectives usually follow the noun and agree: un hombre alt<b>o</b>, una mujer alt<b>a</b>.",
        items: [
          { es: "Esta es mi mujer, Sarah", en: "This is my wife, Sarah", hint: "ES-tah es mee moo-KHER" },
          { es: "Este es mi marido", en: "This is my husband", hint: "ES-teh es mee mah-REE-do" },
          { es: "Tengo dos hijos", en: "I have two children", hint: "TEN-go dos EE-khos" },
          { es: "Un hijo y una hija", en: "A son and a daughter", hint: "oon EE-kho ee OO-nah EE-khah" },
          { es: "Mi madre", en: "My mother", hint: "mee MAH-dreh" },
          { es: "Mi padre", en: "My father", hint: "mee PAH-dreh" },
          { es: "Mis padres", en: "My parents", hint: "mees PAH-dres" },
          { es: "Mi hermano", en: "My brother", hint: "mee er-MAH-no" },
          { es: "Mi hermana", en: "My sister", hint: "mee er-MAH-nah" },
          { es: "Mis nietos", en: "My grandchildren", hint: "mees NYEH-tos" },
          { es: "Es alto y simpático", en: "He's tall and friendly", hint: "es AL-to ee seem-PAH-tee-ko" },
          { es: "Es muy maja", en: "She's really nice", hint: "es mwee MAH-khah", note: "'Majo/maja' is very Spanish for 'lovely'." },
          { es: "Tiene el pelo rubio", en: "She/he has blonde hair", hint: "TYEH-neh el PEH-lo ROO-byo" },
          { es: "¿Cuántos años tiene?", en: "How old is he/she?", hint: "KWAN-tos AH-nyos TYEH-neh" },
        ],
      },
      {
        id: "b3",
        title: "Time, days & dates",
        goal: "Tell the time, name the days and arrange to meet.",
        grammar: "Time uses <b>es la</b> for one o'clock and <b>son las</b> for the rest: <i>es la una</i>, <i>son las tres</i>. Add 'y' for past and 'menos' for to: <i>son las tres y media</i> (3:30).",
        items: [
          { es: "¿Qué hora es?", en: "What time is it?", hint: "keh OH-rah es" },
          { es: "Es la una", en: "It's one o'clock", hint: "es lah OO-nah" },
          { es: "Son las dos", en: "It's two o'clock", hint: "son las dos" },
          { es: "Son las tres y media", en: "It's half past three", hint: "son las tres ee MEH-dyah" },
          { es: "Son las cinco y cuarto", en: "It's quarter past five", hint: "son las THEEN-ko ee KWAR-to" },
          { es: "Son las ocho menos cuarto", en: "It's quarter to eight", hint: "son las OH-cho MEH-nos KWAR-to" },
          { es: "lunes", en: "Monday", hint: "LOO-nes" },
          { es: "martes", en: "Tuesday", hint: "MAR-tes" },
          { es: "miércoles", en: "Wednesday", hint: "MYER-ko-les" },
          { es: "jueves", en: "Thursday", hint: "KHWEH-ves" },
          { es: "viernes", en: "Friday", hint: "VYER-nes" },
          { es: "sábado", en: "Saturday", hint: "SAH-bah-do" },
          { es: "domingo", en: "Sunday", hint: "do-MEEN-go" },
          { es: "hoy", en: "today", hint: "oy" },
          { es: "mañana", en: "tomorrow / morning", hint: "mah-NYAH-nah" },
          { es: "¿Quedamos mañana?", en: "Shall we meet tomorrow?", hint: "keh-DAH-mos mah-NYAH-nah" },
        ],
      },
      {
        id: "b4",
        title: "Numbers, prices & money",
        goal: "Handle the bigger numbers you need for property, rent and bills.",
        items: [
          { es: "treinta", en: "30", hint: "TRAYN-tah" },
          { es: "cuarenta", en: "40", hint: "kwah-REN-tah" },
          { es: "cincuenta", en: "50", hint: "theen-KWEN-tah" },
          { es: "sesenta", en: "60", hint: "seh-SEN-tah" },
          { es: "setenta", en: "70", hint: "seh-TEN-tah" },
          { es: "ochenta", en: "80", hint: "o-CHEN-tah" },
          { es: "noventa", en: "90", hint: "no-VEN-tah" },
          { es: "cien", en: "100", hint: "thyen" },
          { es: "doscientos", en: "200", hint: "dos-THYEN-tos" },
          { es: "quinientos", en: "500", hint: "kee-NYEN-tos" },
          { es: "mil", en: "1,000", hint: "meel" },
          { es: "cincuenta mil euros", en: "50,000 euros", hint: "theen-KWEN-tah meel EW-ros" },
          { es: "¿Cuánto cuesta al mes?", en: "How much per month?", hint: "KWAN-to KWES-tah al mes" },
          { es: "Es demasiado caro", en: "It's too expensive", hint: "es deh-mah-SYAH-do KAH-ro" },
          { es: "¿Puede hacerme un descuento?", en: "Can you give me a discount?", hint: "PWEH-deh ah-THER-meh oon des-KWEN-to" },
        ],
      },
      {
        id: "b5",
        title: "Travel & transport",
        goal: "Take a taxi, hire a car and navigate the airport.",
        items: [
          { es: "Al aeropuerto, por favor", en: "To the airport, please", hint: "al ah-eh-ro-PWER-to" },
          { es: "¿Cuánto cuesta hasta el centro?", en: "How much to the centre?", hint: "KWAN-to KWES-tah AS-tah el THEN-tro" },
          { es: "Pare aquí, por favor", en: "Stop here, please", hint: "PAH-reh ah-KEE" },
          { es: "Quiero alquilar un coche", en: "I want to hire a car", hint: "KYEH-ro al-kee-LAR oon KO-cheh" },
          { es: "¿Está incluido el seguro?", en: "Is insurance included?", hint: "es-TA een-kloo-EE-do el seh-GOO-ro" },
          { es: "¿Dónde está la gasolinera?", en: "Where's the petrol station?", hint: "DON-deh es-TA lah gah-so-lee-NEH-rah" },
          { es: "Lleno, por favor", en: "Fill it up, please", hint: "YEH-no" },
          { es: "Un billete para Madrid", en: "A ticket to Madrid", hint: "oon bee-YEH-teh PAH-rah mah-DREED" },
          { es: "Ida y vuelta", en: "Return (round trip)", hint: "EE-dah ee VWEL-tah" },
          { es: "Solo ida", en: "One way", hint: "SO-lo EE-dah" },
          { es: "¿De qué andén sale?", en: "Which platform does it leave from?", hint: "deh keh an-DEN SAH-leh" },
          { es: "¿A qué hora llega?", en: "What time does it arrive?", hint: "ah keh OH-rah YEH-gah" },
          { es: "He perdido el tren", en: "I've missed the train", hint: "eh per-DEE-do el tren" },
        ],
      },
      {
        id: "b6",
        title: "Your home in Spain",
        goal: "View, rent or buy a property and deal with the practical bits.",
        tip: "Exactly the vocabulary for your six-months-a-year plan — viewings, estate agents and utilities.",
        items: [
          { es: "Buscamos una casa para comprar", en: "We're looking for a house to buy", hint: "boos-KAH-mos OO-nah KAH-sah PAH-rah kom-PRAR" },
          { es: "Queremos alquilar un apartamento", en: "We want to rent an apartment", hint: "keh-REH-mos al-kee-LAR oon ah-par-tah-MEN-to" },
          { es: "¿Cuántas habitaciones tiene?", en: "How many bedrooms does it have?", hint: "KWAN-tas ah-bee-tah-THYO-nes TYEH-neh" },
          { es: "¿Tiene piscina?", en: "Does it have a pool?", hint: "TYEH-neh pees-THEE-nah" },
          { es: "¿Tiene terraza?", en: "Does it have a terrace?", hint: "TYEH-neh teh-RRAH-thah" },
          { es: "Está cerca del mar", en: "It's near the sea", hint: "es-TA THER-kah del mar" },
          { es: "¿Cuánto es la comunidad?", en: "How much are the community fees?", hint: "KWAN-to es lah ko-moo-nee-DAD" },
          { es: "¿Está incluida el agua y la luz?", en: "Are water and electricity included?", hint: "es-TA een-kloo-EE-dah el AH-gwah ee lah looth" },
          { es: "Necesito un fontanero", en: "I need a plumber", hint: "neh-theh-SEE-to oon fon-tah-NEH-ro" },
          { es: "Necesito un electricista", en: "I need an electrician", hint: "neh-theh-SEE-to oon eh-lek-tree-THEES-tah" },
          { es: "¿Cuándo podemos verla?", en: "When can we see it?", hint: "KWAN-do po-DEH-mos VER-lah" },
          { es: "Nos lo pensaremos", en: "We'll think about it", hint: "nos lo pen-sah-REH-mos" },
          { es: "Necesitamos un abogado", en: "We need a lawyer", hint: "neh-theh-see-TAH-mos oon ah-bo-GAH-do", note: "Always use one when buying in Spain." },
        ],
      },
    ],
  },

  /* ===========================================================================
     LEVEL C — FOUNDATION GCSE
     ======================================================================== */
  {
    id: "C",
    code: "C",
    title: "Foundation GCSE",
    blurb: "Build real sentences: the present tense, opinions and everyday topics.",
    lessons: [
      {
        id: "c1",
        title: "All about me",
        goal: "Give a full personal introduction — a GCSE speaking staple.",
        grammar: "Two verbs for 'to be': <b>ser</b> for permanent things (soy, eres, es) and <b>estar</b> for location & mood (estoy, estás, está). 'Soy británico' (I am British) vs 'Estoy cansado' (I am tired).",
        items: [
          { es: "Me llamo... y tengo cincuenta años", en: "My name is... and I'm fifty", hint: "meh YAH-mo ... ee TEN-go theen-KWEN-tah AH-nyos" },
          { es: "Soy británico", en: "I'm British (man)", hint: "soy bree-TAH-nee-ko", note: "Woman: 'británica'." },
          { es: "Vivo en Inglaterra", en: "I live in England", hint: "VEE-vo en een-glah-TEH-rrah" },
          { es: "Estoy casado", en: "I'm married (man)", hint: "es-TOY kah-SAH-do", note: "Woman: 'casada'." },
          { es: "Mi cumpleaños es en mayo", en: "My birthday is in May", hint: "mee koom-pleh-AH-nyos es en MAH-yo" },
          { es: "Trabajo como consultor", en: "I work as a consultant", hint: "trah-BAH-kho KO-mo kon-sool-TOR" },
          { es: "Estoy aprendiendo español", en: "I'm learning Spanish", hint: "es-TOY ah-pren-DYEN-do es-pan-YOL" },
          { es: "Me gusta mucho España", en: "I really like Spain", hint: "meh GOOS-tah MOO-cho es-PAH-nyah" },
          { es: "Mi color favorito es el azul", en: "My favourite colour is blue", hint: "mee ko-LOR fah-vo-REE-to es el ah-THOOL" },
          { es: "Soy una persona tranquila", en: "I'm a calm person", hint: "soy OO-nah per-SO-nah tran-KEE-lah" },
          { es: "En mi tiempo libre leo", en: "In my free time I read", hint: "en mee TYEM-po LEE-breh LEH-o" },
        ],
      },
      {
        id: "c2",
        title: "Present tense & daily routine",
        goal: "Use regular -ar, -er and -ir verbs to describe your day.",
        grammar: "Regular present-tense endings — <b>hablar</b> (to speak): habl<b>o</b>, habl<b>as</b>, habl<b>a</b>, habl<b>amos</b>, habl<b>áis</b>, habl<b>an</b>. <b>comer</b>: como, comes, come… <b>vivir</b>: vivo, vives, vive…",
        items: [
          { es: "Me levanto a las siete", en: "I get up at seven", hint: "meh leh-VAN-to ah las SYEH-teh" },
          { es: "Desayuno café y tostadas", en: "I have coffee and toast for breakfast", hint: "deh-sah-YOO-no kah-FEH ee tos-TAH-das" },
          { es: "Trabajo todo el día", en: "I work all day", hint: "trah-BAH-kho TO-do el DEE-ah" },
          { es: "Como a las dos", en: "I eat at two", hint: "KO-mo ah las dos" },
          { es: "Bebo mucha agua", en: "I drink a lot of water", hint: "BEH-bo MOO-chah AH-gwah" },
          { es: "Vivo cerca del trabajo", en: "I live near work", hint: "VEE-vo THER-kah del trah-BAH-kho" },
          { es: "Hablamos español por la noche", en: "We speak Spanish in the evening", hint: "ah-BLAH-mos es-pan-YOL por lah NO-cheh" },
          { es: "¿A qué hora te levantas?", en: "What time do you get up?", hint: "ah keh OH-rah teh leh-VAN-tas" },
          { es: "Mi mujer cocina muy bien", en: "My wife cooks very well", hint: "mee moo-KHER ko-THEE-nah mwee byen" },
          { es: "Estudiamos juntos", en: "We study together", hint: "es-too-DYAH-mos KHOON-tos" },
          { es: "Me acuesto tarde", en: "I go to bed late", hint: "meh ah-KWES-to TAR-deh" },
        ],
      },
      {
        id: "c3",
        title: "Free time & hobbies",
        goal: "Say what you like doing — with the verb 'gustar'.",
        grammar: "<b>Gustar</b> works backwards: <i>me gusta el fútbol</i> = 'football is pleasing to me'. Use <b>me gusta</b> + one thing/verb, <b>me gustan</b> + plural things. 'Me encanta' = I love it.",
        items: [
          { es: "Me gusta caminar", en: "I like walking", hint: "meh GOOS-tah kah-mee-NAR" },
          { es: "Me gusta el golf", en: "I like golf", hint: "meh GOOS-tah el golf" },
          { es: "Me gustan los deportes", en: "I like sports", hint: "meh GOOS-tan los deh-POR-tes" },
          { es: "Me encanta la playa", en: "I love the beach", hint: "meh en-KAN-tah lah PLAH-yah" },
          { es: "No me gusta nada el frío", en: "I don't like the cold at all", hint: "no meh GOOS-tah NAH-dah el FREE-o" },
          { es: "Toco la guitarra", en: "I play the guitar", hint: "TO-ko lah gee-TAH-rrah" },
          { es: "Veo la televisión", en: "I watch television", hint: "VEH-o lah teh-leh-vee-SYON" },
          { es: "Salgo con mis amigos", en: "I go out with my friends", hint: "SAL-go kon mees ah-MEE-gos" },
          { es: "Los fines de semana descanso", en: "At weekends I rest", hint: "los FEE-nes deh seh-MAH-nah des-KAN-so" },
          { es: "¿Qué te gusta hacer?", en: "What do you like doing?", hint: "keh teh GOOS-tah ah-THER" },
          { es: "Prefiero leer", en: "I prefer to read", hint: "preh-FYEH-ro leh-ER" },
          { es: "Nos gusta viajar", en: "We like to travel", hint: "nos GOOS-tah vyah-KHAR" },
        ],
      },
      {
        id: "c4",
        title: "Food, drink & healthy living",
        goal: "Talk about meals and a healthy lifestyle (a GCSE theme).",
        items: [
          { es: "El desayuno", en: "Breakfast", hint: "el deh-sah-YOO-no" },
          { es: "La comida", en: "Lunch / food", hint: "lah ko-MEE-dah" },
          { es: "La cena", en: "Dinner", hint: "lah THEH-nah" },
          { es: "Como muchas frutas y verduras", en: "I eat lots of fruit and veg", hint: "KO-mo MOO-chas FROO-tas ee ver-DOO-ras" },
          { es: "Intento comer sano", en: "I try to eat healthily", hint: "een-TEN-to ko-MER SAH-no" },
          { es: "No como carne", en: "I don't eat meat", hint: "no KO-mo KAR-neh" },
          { es: "Bebo poco alcohol", en: "I drink little alcohol", hint: "BEH-bo PO-ko al-ko-OL" },
          { es: "Hago ejercicio tres veces por semana", en: "I exercise three times a week", hint: "AH-go eh-kher-THEE-thyo tres VEH-thes por seh-MAH-nah" },
          { es: "Es importante dormir bien", en: "It's important to sleep well", hint: "es eem-por-TAN-teh dor-MEER byen" },
          { es: "Tengo hambre", en: "I'm hungry", hint: "TEN-go AM-breh" },
          { es: "Tengo sed", en: "I'm thirsty", hint: "TEN-go sed" },
          { es: "La dieta mediterránea es muy sana", en: "The Mediterranean diet is very healthy", hint: "lah DYEH-tah meh-dee-teh-RRAH-neh-ah es mwee SAH-nah" },
        ],
      },
      {
        id: "c5",
        title: "Weather & seasons",
        goal: "Describe the weather — useful and a guaranteed GCSE topic.",
        grammar: "Weather mostly uses <b>hace</b> (it makes): <i>hace calor</i> (it's hot), <i>hace frío</i> (it's cold), <i>hace sol</i> (it's sunny). But: <i>está nublado</i> (it's cloudy), <i>llueve</i> (it's raining).",
        items: [
          { es: "¿Qué tiempo hace?", en: "What's the weather like?", hint: "keh TYEM-po AH-theh" },
          { es: "Hace buen tiempo", en: "The weather's good", hint: "AH-theh bwen TYEM-po" },
          { es: "Hace calor", en: "It's hot", hint: "AH-theh kah-LOR" },
          { es: "Hace frío", en: "It's cold", hint: "AH-theh FREE-o" },
          { es: "Hace sol", en: "It's sunny", hint: "AH-theh sol" },
          { es: "Hace viento", en: "It's windy", hint: "AH-theh VYEN-to" },
          { es: "Está nublado", en: "It's cloudy", hint: "es-TA noo-BLAH-do" },
          { es: "Llueve", en: "It's raining", hint: "YWEH-veh" },
          { es: "en primavera", en: "in spring", hint: "en pree-mah-VEH-rah" },
          { es: "en verano", en: "in summer", hint: "en veh-RAH-no" },
          { es: "en otoño", en: "in autumn", hint: "en o-TO-nyo" },
          { es: "en invierno", en: "in winter", hint: "en een-VYER-no" },
          { es: "En verano hace mucho calor aquí", en: "In summer it's very hot here", hint: "en veh-RAH-no AH-theh MOO-cho kah-LOR ah-KEE" },
        ],
      },
      {
        id: "c6",
        title: "Opinions & my town",
        goal: "Give opinions and describe your local area.",
        grammar: "Opinion starters to lift your level: <b>creo que…</b> (I think that…), <b>en mi opinión…</b>, <b>lo bueno es que…</b> (the good thing is…), <b>lo malo es que…</b> (the bad thing is…).",
        items: [
          { es: "Creo que es muy bonito", en: "I think it's very pretty", hint: "KREH-o keh es mwee bo-NEE-to" },
          { es: "En mi opinión, es perfecto", en: "In my opinion, it's perfect", hint: "en mee o-pee-NYON es per-FEK-to" },
          { es: "Lo bueno es que hace sol", en: "The good thing is it's sunny", hint: "lo BWEH-no es keh AH-theh sol" },
          { es: "Lo malo es que hay mucho tráfico", en: "The bad thing is there's lots of traffic", hint: "lo MAH-lo es keh eye MOO-cho TRAH-fee-ko" },
          { es: "Mi pueblo es tranquilo", en: "My town is peaceful", hint: "mee PWEH-blo es tran-KEE-lo" },
          { es: "Hay muchas tiendas", en: "There are lots of shops", hint: "eye MOO-chas TYEN-das" },
          { es: "No hay mucho que hacer", en: "There isn't much to do", hint: "no eye MOO-cho keh ah-THER" },
          { es: "Me parece interesante", en: "It seems interesting to me", hint: "meh pah-REH-theh een-teh-reh-SAN-teh" },
          { es: "Estoy de acuerdo", en: "I agree", hint: "es-TOY deh ah-KWER-do" },
          { es: "No estoy de acuerdo", en: "I disagree", hint: "no es-TOY deh ah-KWER-do" },
          { es: "Para mí, lo mejor es la gente", en: "For me, the best thing is the people", hint: "PAH-rah mee lo meh-KHOR es lah KHEN-teh" },
        ],
      },
    ],
  },

  /* ===========================================================================
     LEVEL D — HIGHER GCSE
     ======================================================================== */
  {
    id: "D",
    code: "D",
    title: "Higher GCSE",
    blurb: "Past, future and conditional tenses — the difference between Foundation and Higher.",
    lessons: [
      {
        id: "d1",
        title: "The past — what I did",
        goal: "Use the preterite to talk about completed actions.",
        grammar: "The <b>preterite</b> (completed past). <b>-ar</b> verbs: habl<b>é</b>, hablaste, habl<b>ó</b>, hablamos, hablasteis, hablaron. <b>-er/-ir</b>: com<b>í</b>, comiste, comi<b>ó</b>… Key irregular: <i>fui</i> (I went / I was).",
        items: [
          { es: "Ayer fui a la playa", en: "Yesterday I went to the beach", hint: "ah-YER fwee ah lah PLAH-yah" },
          { es: "Comí paella", en: "I ate paella", hint: "ko-MEE pah-EH-yah" },
          { es: "Visité un museo", en: "I visited a museum", hint: "vee-see-TEH oon moo-SEH-o" },
          { es: "Compré unos recuerdos", en: "I bought some souvenirs", hint: "kom-PREH OO-nos reh-KWER-dos" },
          { es: "Hablé con un camarero", en: "I spoke with a waiter", hint: "ah-BLEH kon oon kah-mah-REH-ro" },
          { es: "Lo pasé muy bien", en: "I had a great time", hint: "lo pah-SEH mwee byen", note: "Essential GCSE phrase." },
          { es: "Tomamos el sol", en: "We sunbathed", hint: "to-MAH-mos el sol" },
          { es: "Fuimos a un restaurante", en: "We went to a restaurant", hint: "FWEE-mos ah oon res-tow-RAN-teh" },
          { es: "La semana pasada llovió", en: "Last week it rained", hint: "lah seh-MAH-nah pah-SAH-dah yo-VYO" },
          { es: "¿Qué hiciste ayer?", en: "What did you do yesterday?", hint: "keh ee-THEES-teh ah-YER" },
          { es: "No hice nada especial", en: "I didn't do anything special", hint: "no EE-theh NAH-dah es-peh-THYAL" },
        ],
      },
      {
        id: "d2",
        title: "The imperfect & past holidays",
        goal: "Describe how things used to be and set the scene.",
        grammar: "The <b>imperfect</b> = repeated/background past ('used to', 'was -ing'). <b>-ar</b>: habl<b>aba</b>, hablabas, hablaba… <b>-er/-ir</b>: com<b>ía</b>, comías, comía… <i>era</i> (was), <i>había</i> (there was).",
        items: [
          { es: "Cuando era joven, viajaba mucho", en: "When I was young, I travelled a lot", hint: "KWAN-do EH-rah KHO-ven, vyah-KHAH-bah MOO-cho" },
          { es: "El hotel era muy bonito", en: "The hotel was very nice", hint: "el o-TEL EH-rah mwee bo-NEE-to" },
          { es: "Hacía mucho calor", en: "It was very hot", hint: "ah-THEE-ah MOO-cho kah-LOR" },
          { es: "Había mucha gente", en: "There were lots of people", hint: "ah-BEE-ah MOO-chah KHEN-teh" },
          { es: "Íbamos a la playa todos los días", en: "We went to the beach every day", hint: "EE-bah-mos ah lah PLAH-yah TO-dos los DEE-as" },
          { es: "De niño me gustaba nadar", en: "As a child I liked to swim", hint: "deh NEE-nyo meh goos-TAH-bah nah-DAR" },
          { es: "La comida estaba deliciosa", en: "The food was delicious", hint: "lah ko-MEE-dah es-TAH-bah deh-lee-THYO-sah" },
          { es: "El paisaje era impresionante", en: "The scenery was stunning", hint: "el pie-SAH-kheh EH-rah eem-preh-syo-NAN-teh" },
          { es: "Antes vivíamos en la ciudad", en: "We used to live in the city", hint: "AN-tes vee-VEE-ah-mos en lah thyoo-DAD" },
          { es: "Solía levantarme temprano", en: "I used to get up early", hint: "so-LEE-ah leh-van-TAR-meh tem-PRAH-no" },
        ],
      },
      {
        id: "d3",
        title: "The future & plans",
        goal: "Talk about what you're going to do and what will happen.",
        grammar: "Easiest future: <b>ir a</b> + infinitive ('going to'). <i>Voy a comprar</i> (I'm going to buy), <i>vamos a vivir</i> (we're going to live). The true future adds endings to the infinitive: <i>viviré, vivirás, vivirá…</i>",
        items: [
          { es: "Vamos a comprar una casa en España", en: "We're going to buy a house in Spain", hint: "VAH-mos ah kom-PRAR OO-nah KAH-sah en es-PAH-nyah" },
          { es: "Voy a aprender más español", en: "I'm going to learn more Spanish", hint: "voy ah ah-pren-DER mas es-pan-YOL" },
          { es: "Pasaremos seis meses aquí", en: "We'll spend six months here", hint: "pah-sah-REH-mos says MEH-ses ah-KEE" },
          { es: "El año que viene volveremos", en: "Next year we'll come back", hint: "el AH-nyo keh VYEH-neh vol-veh-REH-mos" },
          { es: "Mañana iremos a la playa", en: "Tomorrow we'll go to the beach", hint: "mah-NYAH-nah ee-REH-mos ah lah PLAH-yah" },
          { es: "¿Qué vas a hacer?", en: "What are you going to do?", hint: "keh vas ah ah-THER" },
          { es: "Creo que hará buen tiempo", en: "I think the weather will be good", hint: "KREH-o keh ah-RAH bwen TYEM-po" },
          { es: "Algún día viviremos cerca del mar", en: "One day we'll live near the sea", hint: "al-GOON DEE-ah vee-vee-REH-mos THER-kah del mar" },
          { es: "Vamos a cenar fuera esta noche", en: "We're going to eat out tonight", hint: "VAH-mos ah theh-NAR FWEH-rah ES-tah NO-cheh" },
          { es: "Espero hablar bien pronto", en: "I hope to speak well soon", hint: "es-PEH-ro ah-BLAR byen PRON-to" },
        ],
      },
      {
        id: "d4",
        title: "The conditional — 'I would…'",
        goal: "Be polite and talk about what you would do (lifts your grade).",
        grammar: "The <b>conditional</b> ('would') adds <i>-ía</i> endings to the infinitive: <i>hablaría, comería, viviría</i>. <b>Me gustaría</b> + infinitive ('I would like to…') is the most useful and polite phrase you'll learn.",
        items: [
          { es: "Me gustaría vivir en España", en: "I would like to live in Spain", hint: "meh goos-tah-REE-ah vee-VEER en es-PAH-nyah" },
          { es: "Nos gustaría reservar una mesa", en: "We'd like to book a table", hint: "nos goos-tah-REE-ah reh-ser-VAR OO-nah MEH-sah" },
          { es: "¿Podría ayudarme?", en: "Could you help me?", hint: "po-DREE-ah ah-yoo-DAR-meh", note: "More polite than '¿puede?'." },
          { es: "¿Le importaría repetir?", en: "Would you mind repeating?", hint: "leh eem-por-tah-REE-ah reh-peh-TEER" },
          { es: "Yo en tu lugar, esperaría", en: "If I were you, I'd wait", hint: "yo en too loo-GAR, es-peh-rah-REE-ah" },
          { es: "Comería aquí todos los días", en: "I would eat here every day", hint: "ko-meh-REE-ah ah-KEE TO-dos los DEE-as" },
          { es: "Sería un sueño", en: "It would be a dream", hint: "seh-REE-ah oon SWEH-nyo" },
          { es: "¿Qué harías tú?", en: "What would you do?", hint: "keh ah-REE-ahs too" },
          { es: "Deberíamos practicar más", en: "We should practise more", hint: "deh-beh-REE-ah-mos prak-tee-KAR mas" },
          { es: "Querría más información", en: "I'd like more information", hint: "keh-RREE-ah mas een-for-mah-THYON" },
        ],
      },
      {
        id: "d5",
        title: "Work, study & future plans",
        goal: "Discuss jobs and your plans — a core GCSE higher topic.",
        items: [
          { es: "Trabajo en consultoría", en: "I work in consultancy", hint: "trah-BAH-kho en kon-sool-to-REE-ah" },
          { es: "Soy mi propio jefe", en: "I'm my own boss", hint: "soy mee PRO-pyo KHEH-feh" },
          { es: "Tengo mi propia empresa", en: "I have my own company", hint: "TEN-go mee PRO-pyah em-PREH-sah" },
          { es: "Me gusta mi trabajo", en: "I like my job", hint: "meh GOOS-tah mee trah-BAH-kho" },
          { es: "Es un trabajo exigente", en: "It's a demanding job", hint: "es oon trah-BAH-kho ek-see-KHEN-teh" },
          { es: "Quiero jubilarme pronto", en: "I want to retire soon", hint: "KYEH-ro khoo-bee-LAR-meh PRON-to" },
          { es: "Estoy aprendiendo idiomas", en: "I'm learning languages", hint: "es-TOY ah-pren-DYEN-do ee-DYO-mas" },
          { es: "En el futuro, quiero relajarme", en: "In the future, I want to relax", hint: "en el foo-TOO-ro KYEH-ro reh-lah-KHAR-meh" },
          { es: "Mi objetivo es hablar con fluidez", en: "My goal is to speak fluently", hint: "mee ob-kheh-TEE-vo es ah-BLAR kon floo-ee-DETH" },
          { es: "Estudio un poco cada noche", en: "I study a little each night", hint: "es-TOO-dyo oon PO-ko KAH-dah NO-cheh" },
          { es: "Vale la pena el esfuerzo", en: "The effort is worth it", hint: "VAH-leh lah PEH-nah el es-FWER-tho" },
        ],
      },
      {
        id: "d6",
        title: "Environment & global issues",
        goal: "Express views on big topics — top-end GCSE language.",
        grammar: "Connectives raise your level: <b>sin embargo</b> (however), <b>además</b> (moreover), <b>por lo tanto</b> (therefore), <b>aunque</b> (although), <b>debido a</b> (due to).",
        items: [
          { es: "El medio ambiente es muy importante", en: "The environment is very important", hint: "el MEH-dyo am-BYEN-teh es mwee eem-por-TAN-teh" },
          { es: "Debemos reciclar más", en: "We must recycle more", hint: "deh-BEH-mos reh-thee-KLAR mas" },
          { es: "El cambio climático es un problema grave", en: "Climate change is a serious problem", hint: "el KAM-byo klee-MAH-tee-ko es oon pro-BLEH-mah GRAH-veh" },
          { es: "Hay demasiada contaminación", en: "There's too much pollution", hint: "eye deh-mah-SYAH-dah kon-tah-mee-nah-THYON" },
          { es: "Deberíamos usar el transporte público", en: "We should use public transport", hint: "deh-beh-REE-ah-mos oo-SAR el trans-POR-teh POO-blee-ko" },
          { es: "Sin embargo, no es fácil", en: "However, it isn't easy", hint: "seen em-BAR-go, no es FAH-theel" },
          { es: "Además, cuesta mucho dinero", en: "Moreover, it costs a lot of money", hint: "ah-deh-MAS, KWES-tah MOO-cho dee-NEH-ro" },
          { es: "Por lo tanto, hay que actuar", en: "Therefore, we must act", hint: "por lo TAN-to, eye keh ak-too-AR" },
          { es: "Aunque es difícil, es necesario", en: "Although it's difficult, it's necessary", hint: "OW-nkeh es dee-FEE-theel, es neh-theh-SAH-ryo" },
          { es: "Cada uno puede ayudar", en: "Everyone can help", hint: "KAH-dah OO-no PWEH-deh ah-yoo-DAR" },
          { es: "Es responsabilidad de todos", en: "It's everyone's responsibility", hint: "es res-pon-sah-bee-lee-DAD deh TO-dos" },
        ],
      },
    ],
  },
];

// Make available to the rest of the app (and to a possible Node test).
if (typeof window !== "undefined") window.LEVELS = LEVELS;
if (typeof module !== "undefined") module.exports = { LEVELS };
